spring:
  application:
    name: oauth2-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: autumnli
    url: jdbc:mysql://127.0.0.1:3306/oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false
server:
  port: 8080
mybatis:
  type-aliases-package: com.autumnli.security.server.domain
  mapper-locations: classpath:mapper/*.xml
